# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='id',
        ),
        migrations.AlterField(
            model_name='routes',
            name='route_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
