# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161024_0543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stops',
            name='id',
        ),
        migrations.RemoveField(
            model_name='trips',
            name='id',
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trips',
            name='trip_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
